:sparkles: add classe descricao + testes
iIiqwertyiIi/Trabalho1TP1 pull request #16
Opened 2022-02-20 15:55 UTC by manigoldTLC

close #5 
- Criado classe descrição e seus respectivos testes

2022-02-20 19:58 UTC, iIiqwertyiIi requested changes
Ficou exatamente como o esperado, mas por questão de saber melhor como o código se comporta, fiz algumas sugestões de alteração. Além disso, tem alguns formatos inválidos que não têm verificação.

2022-02-20 19:58 UTC, iIiqwertyiIi commented on domain.cpp
> +    if (descricao.length() > LIMITE) throw invalid_argument("Descrição inválida");
Aqui, eu acho que faltou a verificação de espaços em sequência e a verificação de pontos em sequência.

2022-02-20 19:58 UTC, iIiqwertyiIi commented on test_domain.cpp
> +        estado = FALHA;
Eu gostaria também, que depois de cada catch, tivesse um cout da excessão. Eu fiz isso depois pra ver se todos os "inputs" inválidos realmente estavam lançando excessão.

2022-02-20 19:58 UTC, iIiqwertyiIi commented on domain.cpp
> +    if (descricao.length() > LIMITE) throw invalid_argument("Descrição inválida");
Além disso, acho que a mensagem de lançamento de excessão poderia informar o que estava tentando usar como descrição, no caso.

2022-02-20 19:58 UTC, iIiqwertyiIi commented on test_domain.cpp
> +        if (descricao->getDescricao() == DESCRICAO_INVALIDA) estado = FALHA;
Mesma coisa do catch de cima

2022-02-20 19:58 UTC, iIiqwertyiIi commented on test_domain.h
> +        inline static const string DESCRICAO_INVALIDA = "Aqui tem um exemplo de descricão inválida";
Testar também com espaços em branco em sequência e com pontos em sequência.

2022-02-20 22:50 UTC, iIiqwertyiIi requested changes

2022-02-20 22:50 UTC, iIiqwertyiIi commented on main.cpp
> +    TUDescricao teste1;
Ah, acho que era bom trocar o nome do teste pra testeDescricao ou algo assim.

2022-02-22 01:53 UTC, manigoldTLC commented
acho que foi tudo, nas verificações de pontos e espaçoes seguidos e limite de caracteres eu deixei como um erro padrão, só dizendo que tá inválido.

2022-02-22 13:52 UTC, closed without merging